Use package.json version for ejs version checks
EmulatorJS/EmulatorJS pull request #773
Opened 2024-02-11 21:21 UTC by gantoine

This PR replaces the need to manually bump core version when cores change by relying on the existing version in `package.json`. Comparing versions is done naively against the package.json file hosted in the CDN, which lets us drop `version.json`.

2024-02-11 21:32 UTC, ethanaobrien requested changes

2024-02-11 21:32 UTC, ethanaobrien commented on data/emulator.js
> +const packageJson = require('../package.json');
Is the `require` available in the web browser? How new is this api, I'm trying to hold onto chrome 55-70 support for as long as possible which is why there are several apis I could use where I don't

2024-02-11 21:32 UTC, ethanaobrien commented on data/emulator.js
> +function compareSemver(currentVersion, otherVersion) {
Could we either build this function into the EmulatorJS class or into the check for updates function just to keep organization?

2024-02-11 21:32 UTC, ethanaobrien commented on data/version.json
> -{ "current_version": 401.1 }
Might want to keep this and just hold it back, since older clients still need to fetch for updates

2024-02-12 15:15 UTC, gantoine commented on data/emulator.js
> +const packageJson = require('../package.json');
i think i meant to use `import` here, which is supported in Chrome 61+
<img width="773" alt="Screenshot 2024-02-12 at 10 15 29 AM" src="https://github.com/EmulatorJS/EmulatorJS/assets/3247106/5f150be4-c723-4e6a-aab7-6c82bbe15bfb">

2024-02-23 06:15 UTC, ethanaobrien commented
Hmm, @gantoine - After thinking about this for quite a while I've been reminded that the `data` folder is meant to be packaged separately (+ sometimes cache can be weird and cache one file and not the other), though for the update check that still works perfectly. I do also plan on adding a version check to the cores to make sure they are compatible with emulatorjs (Though this can only be loaded once the core is loaded + ready to play, so its more of a warning than an error). I'd like your thought on this before I make any changes. This is also the last change I have planned for the next release

2024-03-05 17:21 UTC, ethanaobrien commented
Going to close and re-work this method

2024-03-05 17:21 UTC, closed without merging